### ISSUE TITLE
Support Unix socket for database.

### ISSUE THREAD

**Issue by skid9000** [outout14/sacrebleu-dns#3] opened 2020-12-23 12:08 UTC
In config something like this could work :

Conn = socket or ip
Host = unix:/path/to/socket OR ip

Also make the password field optional if unix socket are used.

**Comment by luclu7** [comment] 2020-12-25 01:59
You can already leave the passworld field empty, it's not required btw.

**Comment by outout14** [comment] 2020-12-26 16:11
Commit https://github.com/outout14/sacrebleu-dns/pull/8 by @luclu7 merged in commit https://github.com/outout14/sacrebleu-dns/commit/44f07ca2a2e6ce087fcadff0b4b59489d4db87bf 
The problem is considered resolved.

**Closed as completed by outout14** 2020-12-26 16:11 UTC
Labels: enhancement
